#!/bin/sh
#
# Copyright (c) 2014 The Linux Foundation. All rights reserved.

START=70

start() {

	irq_nss_rps=`grep -m3 nss /proc/interrupts | cut -d ':' -f 1 | tail -n1 | tr -d ' '`
	[ -n "$irq_nss_rps" ] && echo 2 > /proc/irq/$irq_nss_rps/smp_affinity

	# Enable NSS RPS
	sysctl -w dev.nss.general.rps=1 >/dev/null 2>/dev/null

}
# since we don't source /etc/rc.common (openwrt), extra case{} is added here.
case "$1" in
	start)
            start
            if [ "$2" = "autoscaling-disable" ] && [ -e /etc/init.d/perf-test.sh ]; then
                echo "NSS Auto scaling disabled " > /dev/console
                /etc/init.d/perf-test.sh 
            fi
		;;

	stop)
		;;

	restart|force-reload)
		;;

	status)
		exit 1
		;;
esac
